My Arch Programs:
  firefox: firefox browser
  alacritty: terminal emulator
  pavucontrol: audio GUI controller
  ranger: terminal file manager
  vlc: video player
  nsxiv: image viewer
  nmcli: network manager
  nvim: neovim terminal editor
  fish: fish shell
  scrot: a program for take screen captures
  tlp: tlp and tlp ui for battery config (acpid for the controller)
  asusctl: asus laptop hadware controller

Dev enviroments:
  nodejs_npm
  python3_pip
  go_lang
  clang (with make and cmake)
  rust
  bun
