require 'user.packer'
require 'user.devicons'
require 'user.editor'
require 'user.diagnostic'
require 'user.theme'
require 'user.lualine'
require 'user.telescope'
require 'user.navigation'
require 'user.nvim-tree'
require 'user.comment'
require 'user.indent'
require 'user.git'
require 'user.treesitter'
require 'user.lsp'
require 'user.cmp'
require 'user.toggleterm'
-- TODO: integrate the clipboard in the editor
-- TODO: put the autopairs plugin (https://github.com/windwp/nvim-autopairs)